[project]
name = "internship-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "google-api-python-client>=2.200.0",
    "google-auth-oauthlib>=1.4.1",
    "psycopg2-binary>=2.9.13",
    "python-dotenv>=1.2.3",
    "python-jose>=3.5.0",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]

